### ISSUE TITLE
The extension is not compatible with events calendar 6.7.0

### ISSUE THREAD

**Issue by kaurman** [mt-support/tec-labs-remove-past-events#8]
It seems that the extension is no longer compatible with the current version of the Events Calendar as there have been considerable changes in its source. As it is, using the extension does not add any options to the settings view and from what I can tell, it makes perfect sense, due to the aforementioned changes.

**Comment by andrasguseo** [comment]
Hi @kaurman 
We just released version 1.2.2 which should make it compatible with the new admin UI.
You can grab it from [here](https://github.com/mt-support/tec-labs-remove-past-events/releases/download/1.2.2/tec-labs-remove-past-events-1.2.2.zip) directly or from the [extension page](https://theeventscalendar.com/extensions/remove-past-events/).

Cheers,
Andras
